name: CI Kata-Tennis-Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code source dans le dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache les dépendances Maven pour accélérer le build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Compile le projet avec Maven
      - name: Build with Maven
        run: mvn clean install

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t kata-tennis-game .

      # Exécute les tests
      - name: Run tests
        run: mvn test
